name: release
on:
  push:
    paths-ignore: 
      - '**/*.md'
      - '**/*.yml'
    tags:        
      - 'v-*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "appsettings.json"
        token: ${{ secrets.GITHUB_TOKEN }}
