name: add-release

on:
  push:
    paths-ignore: 
      - '**/*.md'
      - '**/*.yml'
    tags:        
      - 'v-*'
    
jobs:
  build-dotnet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish AgileConfig.Server.Apisite/AgileConfig.Server.Apisite.csproj -c Release
    - uses: actions/upload-artifact@v2
      with:
        name: agileconfig-server
        path: AgileConfig.Server.Apisite/bin/Release/netcoreapp3.1/publish/
    - name: create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: AgileConfig.Server.Apisite/bin/Release/netcoreapp3.1/publish/
        token: ${{ secrets.GITHUB_TOKEN }}
